# Generated by Django 2.2.15 on 2020-08-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Admin'), (8, 'Owner'), (2, 'Fanat'), (1, 'Hooligun')], default=1),
        ),
    ]
