# Generated by Django 2.2.15 on 2020-08-22 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_eventplayer_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventplayer',
            name='estimation',
        ),
        migrations.RemoveField(
            model_name='eventplayer',
            name='user',
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimation', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.EventPlayer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
